# Copyright 2022 D2iQ, Inc. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

apiVersion: apps/v1
kind: DaemonSet
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ include "csi-driver-trusted-ca.name" . }}
  labels:
    {{ include "csi-driver-trusted-ca.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      app: {{ include "csi-driver-trusted-ca.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "csi-driver-trusted-ca.name" . }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "csi-driver-trusted-ca.name" . }}
      containers:

        - name: node-driver-registrar
          image: "{{ .Values.nodeDriverRegistrarImage.repository }}:{{ default .Chart.AppVersion .Values.nodeDriverRegistrarImage.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - -v={{ .Values.app.logLevel }}
            - --csi-address=/plugin/csi.sock
            - --kubelet-registration-path={{ .Values.app.kubeletRootDir }}/plugins/csi-driver-trusted-ca/csi.sock
          env:
            - name: KUBE_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          volumeMounts:
            - name: plugin-dir
              mountPath: /plugin
            - name: registration-dir
              mountPath: /registration

        - name: liveness-probe
          image: "{{ .Values.livenessProbeImage.repository }}:{{ default .Chart.AppVersion .Values.livenessProbeImage.tag }}"
          args:
            - --csi-address=/plugin/csi.sock
            - --probe-timeout=3s
            - --health-port={{.Values.app.livenessProbe.port}}
            - -v={{ .Values.app.logLevel }}
          imagePullPolicy: {{ .Values.livenessProbeImage.pullPolicy }}
          volumeMounts:
            - name: plugin-dir
              mountPath: /plugin

        - name: csi-driver-trusted-ca
          securityContext:
            privileged: true
            capabilities:
              add: ["SYS_ADMIN"]
            allowPrivilegeEscalation: true
          image: "{{ .Values.image.repository }}:{{ default .Chart.AppVersion .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args :
            - --log-level={{ .Values.app.logLevel }}
            - --driver-name={{ .Values.app.driver.name }}
            - --node-id=$(NODE_ID)
            - --endpoint=$(CSI_ENDPOINT)
            - --data-root=csi-data-dir
            - --trusted-certs-source={{ required "A valid .Values.trustedCertsSource entry required!" .Values.trustedCertsSource }}
          env:
            - name: NODE_ID
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: CSI_ENDPOINT
              value: unix://plugin/csi.sock
          volumeMounts:
            - name: plugin-dir
              mountPath: /plugin
            - name: pods-mount-dir
              mountPath: {{ .Values.app.kubeletRootDir }}/pods
              mountPropagation: "Bidirectional"
            - name: csi-data-dir
              mountPath: /csi-data-dir
              mountPropagation: "Bidirectional"
          ports:
            - containerPort: {{.Values.app.livenessProbe.port}}
              name: healthz
          livenessProbe:
            httpGet:
              path: /healthz
              port: healthz
            initialDelaySeconds: 5
            timeoutSeconds: 5
          resources:
            {{- toYaml .Values.resources | nindent 12 }}

      {{- if .Values.nodeSelector }}
      nodeSelector: {{-  toYaml .Values.nodeSelector | nindent 8 }}
      {{- end }}

      tolerations:
        {{- toYaml .Values.tolerations | nindent 8 }}

      {{- with .Values.priorityClassName }}
      priorityClassName: {{ . | quote }}
      {{- end }}

      volumes:
        - name: plugin-dir
          hostPath:
            path: {{ .Values.app.kubeletRootDir }}/plugins/csi-driver-trusted-ca
            type: DirectoryOrCreate
        - name: pods-mount-dir
          hostPath:
            path: {{ .Values.app.kubeletRootDir }}/pods
            type: Directory
        - hostPath:
            path: {{ .Values.app.kubeletRootDir }}/plugins_registry
            type: Directory
          name: registration-dir
        - hostPath:
            path: {{ .Values.app.driver.csiDataDir }}
            type: DirectoryOrCreate
          name: csi-data-dir
