# Copyright 2022 D2iQ, Inc. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

apiVersion: v1
kind: ServiceAccount
{{- with .Values.imagePullSecrets }}
imagePullSecrets:
    {{- toYaml . | nindent 8 }}
{{- end }}
metadata:
  labels:
{{ include "csi-driver-trusted-ca.labels" . | indent 4 }}
  name: {{ include "csi-driver-trusted-ca.name" . }}
