# Copyright 2022 D2iQ, Inc. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ include "csi-driver-trusted-ca.name" . }}
  labels:
    {{ include "csi-driver-trusted-ca.labels" . | nindent 4 }}
{{- with .Values.imagePullSecrets }}
imagePullSecrets:
    {{- toYaml . | nindent 8 }}
{{- end }}
